name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-13, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install baoengineer/tap/byom
      - run: brew test byom
      - run: byom --version
