name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-15-intel, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: Homebrew/actions/setup-homebrew@fccef3b26268fc4a788fd7ad7c189f3a105cbf13 # main
      - run: brew install baoengineer/tap/byom
      - run: brew test byom
      - run: byom --version
